version: 2.1

orbs:
  node: circleci/node@5.1.0

workflows:
  build-and-test:
    jobs:
      - node/run:
          app-dir: frontend
          virsion: "16.18"
          pkg-manager: yarn
          yarn-run: lint