version: 2.1

orbs:
  node: circleci/node@5.1.0

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-test:
    - node/test:
        app-dir: frontend
        version: "16.18"
        pkg-manager: yarn